version: '3.9'

services:
  backend:
    container_name: ukrenergy_backend
    build:
      context: ./backend
    ports:
      - "127.0.0.1:3000:3000"
    restart: "no"
    volumes: 
      - "./backend/uploads:/app/uploads"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ukrenergy_db
    image: postgres:15.1
    ports:
     - "127.0.0.1:5432:5432"
    restart: "no"
    volumes:
      - "./db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=ukrenergy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
